---
name: "Build"
"on":
  pull_request:
    branches:
    - "master"
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@master"
    - uses: "actions/setup-java@master"
      with:
        distribution: "adopt"
        java-version: "11"
    - uses: "actions/cache@master"
      with:
        path: "~/.gradle/caches"
        key: "${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}"
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: "actions/cache@master"
      with:
        path: "~/.gradle/wrapper"
        key: "${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}"
        restore-keys: |
          ${{ runner.os }}-gradlew-
    - run: |
        chmod +x gradlew
        ./gradlew build
